### ISSUE TITLE
spell checker

### ISSUE THREAD

**Issue by MikeUnwalla** [MicrosoftDocs/microsoft-style-guide#13]
I suggest that you revert to 'spelling checker', as in MMOS 4th edition.

Reason: people do a check of the spelling in a document. They do not do a check of the spells. (Only Harry Potter [https://en.wikipedia.org/wiki/Harry_Potter] and friends need a spell checker.)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a520382-d6b5-5424-206a-79429264feb9
* Version Independent ID: b601cbf9-613e-3d45-1959-40e62145ff1e
* Content: [spell checker - Microsoft Style Guide](https://docs.microsoft.com/en-gb/style-guide/a-z-word-list-term-collections/s/spell-checker)
* Content Source: [styleguide/a-z-word-list-term-collections/s/spell-checker.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/s/spell-checker.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Microsoft changed its position about this to align with American Heritage Dictionary, which has added [spell checker](https://ahdictionary.com/word/search.html?q=spell+checker) as a noun.  “Spelling checker” might be more logical, but English is often illogical.

That said, Microsoft still prefers “check spelling” as the verb form because it sounds more human. And ideally, you’d refer to a specific tool by the name used in the UI, especially if the goal is to give the user the information they need to complete a task. It's just that “spell checker” is acceptable when you need a generic term for any tool that checks spelling.
