### ISSUE TITLE
Definitions of the words button and icon

### ISSUE THREAD

**Issue by KA-1** [MicrosoftDocs/microsoft-style-guide#14]
Hello,
I would like to propose that the definitions of the words “button” and “icon” in the Microsoft Writing Style Guide be changed to differentiate that buttons have functionality and icons do not.
•	The Microsoft definitions are similar to the definitions used by the International Standards Organization (ISO) (https://www.iso.org/obp/ui/#iso:std:iso-iec:2382:ed-1:v1:en:term:2123770) but I figure it might be easier to convince you, the editors of the Microsoft Writing Style Guide, to change your definitions rather than to convince the ISO ☺

The Microsoft definition of icon is: Use only to describe a graphic representation of an object that a customer can select and open, such as a drive, folder, document, or app, which seems to specify that the graphic representation is linked to functionality. But, I’m not certain what the definition means or how to apply it.
•	However, this definition does not necessarily agree with definitions from other sources. Historically the word “icon” used to mean only an image.
•	The definition in the Oxford dictionaries, that an icon is “Computing - A symbol or graphic representation on a screen of a program, option, or window” (https://en.oxforddictionaries.com/definition/icon), does not specify that the icon has any functionality.
•	And, in both the SAP and uPerform applications icons are only symbols with no functionality.
Because the Microsoft (and ISO) definitions of icon and button seem to imply that they both have functionality, this has caused some confusion, in this government department, in documenting SAP procedures. 
•	Because of their confusion, our SAP training team has tried to clarify the terms further, in their standards guide.
 
•	But, although the text in their guide states “Icons are only images” the pictures to the right of the text   are of buttons with functionality .
•	Their definition that “Buttons have text written on them” is a definition that does not seem to have any precedent and that I have not seen anywhere else. They were trying to clarify the terms button and icon and, to do that, they invented a new definition for button – one that they could understand.
To avoid such confusion, I would propose that the definitions in the Microsoft Writing Style Guide be changed to something like:
•	a button is a GUI object that triggers an action in an application
•	an icon is an image that has no functionality
And, if one or more term is needed for “an object that a customer can select and open, such as a drive, folder, document, or app” perhaps new terms could be developed (e.g., “application button”).
Thanks,
Karen 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 584d59ff-7ac1-cb60-e33f-61370ca60824
* Version Independent ID: db5f305b-6069-de3d-16be-9d141af9d3b7
* Content: [icon - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/icon)
* Content Source: [styleguide/a-z-word-list-term-collections/i/icon.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/i/icon.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi Karen,

Thanks for contacting us and sending so much context and background.

Yes, at Microsoft, an “icon” does have some kind of functionality. It might appear alone or be accompanied by a label, but it’s not merely a graphic. 
That said, we try to avoid writing about the UI element itself and just tell the user what they need to know to get something done. (For example, “Select [image of Settings icon]” vs. “Select the Settings icon.”)
So perhaps, if you’re documenting SAP procedures, you can use the SAP terminology and the difference in the two platform’s definitions of “icon” doesn’t need to be an issue.

I’ll pass on your request to some people who are more familiar with the Windows OS and Office design platforms, and I’ll let you know if they have any insights or additional info. 
Regards,
Catherine

From: KA-1 <notifications@github.com> 
Hello,
I would like to propose that the definitions of the words “button” and “icon” in the Microsoft Writing Style Guide be changed to differentiate that buttons have functionality and icons do not.
• The Microsoft definitions are similar to the definitions used by the International Standards Organization (ISO) (https://www.iso.org/obp/ui/#iso:std:iso-iec:2382:ed-1:v1:en:term:2123770) but I figure it might be easier to convince you, the editors of the Microsoft Writing Style Guide, to change your definitions rather than to convince the ISO ☺
The Microsoft definition of icon is: Use only to describe a graphic representation of an object that a customer can select and open, such as a drive, folder, document, or app, which seems to specify that the graphic representation is linked to functionality. But, I’m not certain what the definition means or how to apply it.
• However, this definition does not necessarily agree with definitions from other sources. Historically the word “icon” used to mean only an image.
• The definition in the Oxford dictionaries, that an icon is “Computing - A symbol or graphic representation on a screen of a program, option, or window” (https://en.oxforddictionaries.com/definition/icon), does not specify that the icon has any functionality.
• And, in both the SAP and uPerform applications icons are only symbols with no functionality.
Because the Microsoft (and ISO) definitions of icon and button seem to imply that they both have functionality, this has caused some confusion, in this government department, in documenting SAP procedures.
• Because of their confusion, our SAP training team has tried to clarify the terms further, in their standards guide.
• But, although the text in their guide states “Icons are only images” the pictures to the right of the text are of buttons with functionality .
• Their definition that “Buttons have text written on them” is a definition that does not seem to have any precedent and that I have not seen anywhere else. They were trying to clarify the terms button and icon and, to do that, they invented a new definition for button – one that they could understand.
To avoid such confusion, I would propose that the definitions in the Microsoft Writing Style Guide be changed to something like:
• a button is a GUI object that triggers an action in an application
• an icon is an image that has no functionality
And, if one or more term is needed for “an object that a customer can select and open, such as a drive, folder, document, or app” perhaps new terms could be developed (e.g., “application button”).
Thanks,
Karen

**Comment by KA-1** [comment]
Thanks Catherine.

Karen

**Comment by camind** [comment]
hi Karen,
It doesn't look like Microsoft is going to be changing its style for these terms, so I'm going to close this issue. 
Regards,
Catherine

**Comment by KA-1** [comment]
Hi Catherine,

Well, I tried. Thanks for letting me know.

Regards,

Karen
