### ISSUE TITLE
Press vs Select for keyboards

### ISSUE THREAD

**Issue by DITA-dude** [MicrosoftDocs/microsoft-style-guide#151]
I'm willing to make the shift to "Select" for most UI interactions. However, "Select Ctrl+Alt+Delete" feels awkward. Seems like "Press" is more natural for physical keyboards AND would be acceptable for on-screen ones as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ad46ad-342d-da22-47a6-504ce7a06a95
* Version Independent ID: 3f8c7233-e250-e7f7-faff-c90b91ff03c7
* Content: [Describing interactions with UI - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui#feedback)
* Content Source: [styleguide/procedures-instructions/describing-interactions-with-ui.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/procedures-instructions/describing-interactions-with-ui.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by ashishguptaiitb** [comment]
Agree with the above. Largely our input devices have been and continue to be keyboard and mouse. On-screen keyboards, voice commands, joysticks, etc. have only very recently become mainstream (have they for end-users of enterprise software?) Over the years, we writers have well trained our readers to understand press, enter, click, etc. in our docs. Most is colloquial usage as press comes from physically pressing of keys, enter comes from pressing the Return key, and click comes from the sound made by a mouse. At least now and at least for on-screen keyboards press verb will work well because our input devices haven't changed much. 

I am compelled to say that if the ratio of users using varied input devices is high, then consider using alternatives like select and choose. The MS Style Guide does a great job at explaining these. Consider cases of writing for mobile app (all touch with no keyboard!), for motion-sensing devices like Kinect, then drop press and click verbs altogether.

----

Also, we as a community ought to train our readers for the future as well. The due date to start doing so was yesterday! 😃 we cannot keep on changing the docs! With touch devices, it is tap instead of click in the coming decade. And in the next to the coming decade, it'll be some gesture instead of tap.

"Select a combination of x, y, and z keys" makes sense for on-screen keyboards and voice commands. It reads weird to me as well. Maybe we too are conditioned to read it as 'Press x, y, and z.' Isn't that good for other users to be conditioned this way so that there is no ambiguity when they read instructions. When using an on-screen touch keyboard, if it reads press, then they know that they have to tap.

**Comment by mbellthomson** [comment]
Hello, and thank you for your feedback on the Microsoft Writing Style Guide. 

Microsoft style purposefully says to use "select" as the verb for user interaction with buttons.
If you're using a mouse, you click a button, but if you're using a tablet or phone, you might tap it. If you're using an assistive device, you might use some other action.

To support customers of all abilities and the many different ways that people use their devices, we document all the ways that customers can interact with the UI. Most of the time, this means writing the procedure in such a way that it uses input-neutral verbs ("select"). And then the documentation also includes an article that explains how to interact with the product using each available input method. In an article or procedure that's specifically about mouse procedures, it would be appropriate to use "click."

You can find more info in [Describing alternative input methods](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods).
Thanks!
-Melissa
