### ISSUE TITLE
5 PM or 5.00 PM?

### ISSUE THREAD

**Issue by chanakavp** [MicrosoftDocs/microsoft-style-guide#16]
Which one is correct? 5 PM or 5.00 PM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca6ef4b-d12b-5b40-0f6f-ff4af5b0fa5f
* Version Independent ID: b6468d10-6262-efa8-45e2-b1c5a3231e73
* Content: [Date and time terms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/date-time-terms)
* Content Source: [styleguide/a-z-word-list-term-collections/term-collections/date-time-terms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/term-collections/date-time-terms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Either 5 PM or 5:00 PM can be used. We don't have a specific guideline and leave it up to the writer's judgment. Most of the time, you'll probably include the minutes because you're referencing several times, and you'll want to be consistent. 

For example, if you're saying, "The session lasts from 3:30 PM to 5:00 PM," it makes sense to use "5:00." But it would be OK to use the less formal wording, "The social event doesn't start until after 5 PM."
