### ISSUE TITLE
Hyphenated compound question

### ISSUE THREAD

**Issue by rogerbgt** [MicrosoftDocs/microsoft-style-guide#2]
Please can you explain the difference in capitalization of the second word in your two examples?
Self-Paced Training for Microsoft Visual Studio
and
Five Essential Snap-ins for Microsoft Management Console

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a047b5-771e-7a2a-d6ad-4038dd872397
* Version Independent ID: 9749bff4-8583-552b-284d-eee6d6340006
* Content: [Capitalization - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/capitalization)
* Content Source: [styleguide/capitalization.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/capitalization.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Sure--those two titles are examples of the guideline “Capitalize the second part of a hyphenated compound if it would be capitalized without the hyphen.”
In the word “Self-Paced,” the word “Paced” would be capitalized if it appeared by itself, without “Self-“ attached to it.

But in the second example, “ins” (or “in”) wouldn’t be capitalized if it appeared by itself, so it’s lowercase. And the reason it would be lowercase is because “in” by itself is a preposition (though the compound word “snap-in” is a noun).

**Comment by rogerbgt** [comment]
Nice explanation. Thanks. Just to clarify, "Paced" would be capitalised if it appeared by itself because it would be the first word?

**Comment by camind** [comment]
Hi Roger,
First, to answer the other question you asked in a different thread. This example is meant to show correct capitalization when you’re using title-style capitalization. So in this example, “Paced” is capitalized because it’s a verb (or participle, which is a verb form). And in title-style capitalization, verbs, nouns, adjectives, adverbs, and pronouns are capped. Therefore, in title-style capitalization, a word like “Paced” is capped whether it appears by itself or as part of a compound modifier.

For your second question, about writing content that refers to app UI: the rule of thumb in Microsoft style is to use the capitalization shown in the [Formatting text in instructions](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/formatting-text-in-instructions) topic, *unless you need to match the UI.* 

In the "Formatting text in instructions" topic, the entry for each UI element (for example, buttons and check boxes), says, “Use sentence-style capitalization unless you need to match the UI.” 

So in your example, I would use "Welcome Letter and Customer Retention Summary report" to match the capping in the UI. (And I agree with your capping of "report." The generic part of the phrase, like "report," "feature," "option," "check box," etc., is lowercase.)

Microsoft style *aims* to use sentence-style capitalization for UI labels/text, but that isn’t always possible--some existing app functionality hasn’t yet been updated to use sentence-style capping. We think the user experience is best served by having the documentation match what the user actually sees in the UI.

FYI, for more developer-focused, technical content, there’s another version of this topic called [Formatting developer text elements]( https://docs.microsoft.com/en-us/style-guide/developer-content/formatting-developer-text-elements), which might be especially useful for the content that you work on.

I hope this helps!  Catherine

**Comment by rogerbgt** [comment]
Hi Catherine,
Wow, thanks. Really appreciate your reply. Apart from your practical assistance with my question, the fact that you’ve responded so quickly and thoroughly is awesome customer support.

I really like that you’ve enabled feedback and comments on your style guide.

Thanks,
Roger

Roger Brouwer
Senior Technical Writer

T: +64 9 966 6090
E: roger.brouwer@gentrack.com<mailto:roger.brouwer@gentrack.com>
W: www.gentrack.com<http://www.gentrack.com/>

[Gentrack Email Footer]

**Comment by camind** [comment]
You're very welcome, and thank you for the kind words. I hope the style guide can continue to support you in your work! Regards, Catherine
