### ISSUE TITLE
Cross-reference issue

### ISSUE THREAD

**Issue by pallabiwrites** [MicrosoftDocs/microsoft-style-guide#257]
[The link to the "Capitalization" section is not working. It is generating a 404 error. Please fix the link: https://docs.microsoft.com/en-us/style-guide/capitalization]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbd6c9a-7000-1b08-7b83-e03f2a7781ff
* Version Independent ID: 6a183599-bb95-007c-41e4-308605df5638
* Content: [Hyphens - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens)
* Content Source: [styleguide/punctuation/dashes-hyphens/hyphens.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/punctuation/dashes-hyphens/hyphens.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by maitesadaba** [comment]
Done, link corrected. Thank you very much for this useful piece of feedback.
Have a lovely day!
Maite

From: pallabiwrites ***@***.***>
Sent: Thursday, August 5, 2021 9:40 AM
To: MicrosoftDocs/microsoft-style-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftDocs/microsoft-style-guide] Cross-reference issue (#257)


[The link to the "Capitalization" section is not working. It is generating a 404 error. Please fix the link: https://docs.microsoft.com/en-us/style-guide/capitalization]

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: ddbd6c9a-7000-1b08-7b83-e03f2a7781ff
  *   Version Independent ID: 6a183599-bb95-007c-41e4-308605df5638
  *   Content: Hyphens - Microsoft Style Guide<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fstyle-guide%2Fpunctuation%2Fdashes-hyphens%2Fhyphens&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115649244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vSsABaqJq8H7FTLvWgmB7GEM%2BK9oFSOxvqyO%2FSvJT4k%3D&reserved=0>
  *   Content Source: styleguide/punctuation/dashes-hyphens/hyphens.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fblob%2Fmaster%2Fstyleguide%2Fpunctuation%2Fdashes-hyphens%2Fhyphens.md&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115659205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ccNNL75UpvJhKxykWpV9EXlqG7LN4QwExpXWps6P7gY%3D&reserved=0>
  *   Product: non-product-specific
  *   GitHub Login: @pallep<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpallep&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115659205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4GFy1jCLsZ3Ahzv6p%2BxSmCWH0vQWGOOVivKoZ32HYRc%3D&reserved=0>
  *   Microsoft Alias: pallep

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-style-guide%2Fissues%2F257&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115669157%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i0KOMgMH69Zcq8YiNkZ%2F1iexS0GHPkvB2pvJIV05J00%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASXUAR3UAJYNHGQWUGRGWILT3I55NANCNFSM5BTD43SQ&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115669157%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TbOpVYxb7Fahm5lhOwjKYSF5dZtkvJHwpbc0DnowQMQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115679107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pJUHIiAOoQu9MDUEBbOoCleJNUFqfqJMSBL%2F8J9VJZc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cv-maites%40microsoft.com%7C324c701e6baa498d76fa08d957e43ebb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637637460115679107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0vgqk82N5mD3NkDIIKZe4Js13ye1zwlQU2V0BG38418%3D&reserved=0>.
