### ISSUE TITLE
UBS is NOT an acronym

### ISSUE THREAD

**Issue by LLawsonBruton** [MicrosoftDocs/microsoft-style-guide#297]
[Enter feedback here]
There are acronyms like NASA and then there are abbreviations like USB. On this page, you have many abbreviations listed as acronyms. 
I won't go into the difference between an acronym and an abbreviation; I am sure you know the difference.
Thanks - lindajobruton@outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d30bb26-5486-e2d9-851b-47ceeb6d07b5
* Version Independent ID: 295d184a-a254-acea-6185-b14346fb0634
* Content: [Acronyms - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/acronyms)
* Content Source: [styleguide/acronyms.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/acronyms.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by pivic** [comment]
Actually, they're both abbreviations. Abbreviations that are spelled out, like USB, are initialisms.

**Comment by S-LRaillard** [comment]
Hi @LLawsonBruton, thanks for your feedback. We use "abbreviation" as the umbrella term for a variety of shortened forms, including both acronyms and initialisms. An "initialism" is a kind of acronym, but since that term is less common for folks, we use "acronym" instead. As @pivic has noted, USB is most precisely an initalism (but it is also, in descending order of precision, an acronym and an abbrevation).
