### ISSUE TITLE
Why should not use OSS as abbreviation of open-source software?

### ISSUE THREAD

**Issue by DuyDang007** [MicrosoftDocs/microsoft-style-guide#299]
[Enter feedback here]

Hi,

I see many websites and even in our company use "OSS" a lot. But why do you not recommend it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5c880d4-4341-30e7-d4d4-afadff82d239
* Version Independent ID: 4bb463f8-9e12-5f61-d691-08d372af7be7
* Content: [open source, open-source - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source)
* Content Source: [styleguide/a-z-word-list-term-collections/o/open-source.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/o/open-source.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by pivic** [comment]
I'm just a regular person who's not affiliated with MS, but, were I to wager a guess, I'd say 'OSS' is an abbreviation that is jargon. In other words, because the MS Writing Style Guide avoids the use of jargon as often as possible, it's better to write out the term.

I guess a look in major dictionaries like Merriam-Webster, Oxford, and American Heritage won't disclose definitions for 'OSS'; in other words, the popularity of the term is minute.

**Comment by DuyDang007** [comment]
Thanks for your answer. My understanding is if the document point to general users who are not familiar with software development term, we must not use OSS. If the document are for software developers, it is okay to use OSS
