### ISSUE TITLE
Accessibility term collection is no longer available

### ISSUE THREAD

**Issue by natalevoshko** [MicrosoftDocs/microsoft-style-guide#325]
[Enter feedback here]
Hi there,
this page seems to be not available anymore
https://github.com/MicrosoftDocs/microsoft-style-guide-pr/blob/main/styleguide/a-z-word-list-term-collections/term-collections/accessibility-terms.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3fbd78-e2ad-bfc6-9f2f-13f739b57937
* Version Independent ID: 9ce3e837-12b6-e7b8-6bef-597ec2570dbb
* Content: [Bias-free communication - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/bias-free-communication)
* Content Source: [styleguide/bias-free-communication.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/bias-free-communication.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by vDonGlover** [comment]
The file is actually there in there in the repo. There is a similar issue with the link for [Accessibility guidelines and requirements].
It appears to be a rendering issue since the markdown for the links, at first glance, appears to be correct. 
They neet to rebuild and republish the page and check if the issue persists.

**Comment by S-LRaillard** [comment]
Hi @natalevoshko this issue has been fixed, please close the ticket!
