### ISSUE TITLE
Time zones and AM/PM example

### ISSUE THREAD

**Issue by stephyacek** [MicrosoftDocs/microsoft-style-guide#335]
Hello,

I was looking for clarification regarding how to use AM and PM with a time zone. Example: Is it _10:00 AM PT_ or _10:00 AM, PT_ or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4ab3f5-d7de-1853-6f11-16e761b9698e
* Version Independent ID: 3901f044-2b3e-5f86-79b8-0cce3382c49c
* Content: [Welcome - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)
* Content Source: [styleguide/welcome/index.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/welcome/index.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi there,

I'm the editor for the Microsoft Writing Style Guide and want to thank you for raising this issue. There is some guidance about this issue here: https://learn.microsoft.com/en-us/style-guide/numbers
In short, if you will be using both AM/PM markers and specifying a time zone, you should spell out the time zone and not use an abbreviation: "The event starts at 5∶00 PM Pacific Time."

Another option would be to use 24h time if it is used in the local market.

Hope this helps!
