### ISSUE TITLE
Recommended wording for check boxes converted to toggle switches 

### ISSUE THREAD

**Issue by burkbry** [MicrosoftDocs/microsoft-style-guide#35]
What wording changes are recommended for situations where UI elements are converted from check boxes to toggle switches? For example, What do you recommend the wording for "Select the ABC check box." or "Clear the ABC check box." be changed to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ad46ad-342d-da22-47a6-504ce7a06a95
* Version Independent ID: 3f8c7233-e250-e7f7-faff-c90b91ff03c7
* Content: [Describing interactions with UI - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui)
* Content Source: [styleguide/procedures-instructions/describing-interactions-with-ui.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/procedures-instructions/describing-interactions-with-ui.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hi, 
Good question. The [toggle](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/t/toggle) topic says to "use *switch, turn on,* or *turn off* with the name of the toggle key or command to describe what the customer must do."

We've also found that including the word "toggle" can be helpful for users who are blind or have low vision. So, for example, we would be more likely to say, "To keep all applied filters, turn on the **Pass all filters** toggle" rather than "To keep all applied filters, turn on **Pass all filters**."

You raise a good point--that guidance should also be in the [Describing interactions with UI](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui) topic. We'll work on adding this.
