### ISSUE TITLE
p-code is not an abbreviation for pseudocode

### ISSUE THREAD

**Issue by george-at-navihealth** [MicrosoftDocs/microsoft-style-guide#413]
Read the Wikipedia article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10a1f9ef-88fe-a710-35e1-b006854931d9
* Version Independent ID: 727cada7-e180-cb9a-1f9c-9d85ca5d88eb
* Content: [p-code - Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/p-code)
* Content Source: [styleguide/a-z-word-list-term-collections/p/p-code.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/main/styleguide/a-z-word-list-term-collections/p/p-code.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by S-LRaillard** [comment]
Hi there @george-at-navihealth  - indeed, the[ Wikipedia article ]( https://en.wikipedia.org/wiki/P-code_machine) explains the Microsoft-specific use of "p-code," which is why it is included in the MWSG (we are not attempting to duplicate the dictionary, but call out specific places where Microsoft guidance is unique or precise). see especially the section: 

Microsoft P-Code
P-Code is a name for several of Microsoft's proprietary intermediate languages. They provided an alternate binary format to machine code. At various times, Microsoft have said p-code is an abbreviation for either packed code[8] or pseudo code.
