### ISSUE TITLE
What about the immediately preceding version?

### ISSUE THREAD

**Issue by ahungund** [MicrosoftDocs/microsoft-style-guide#43]
If we are talking about the version immediately preceding the one being discussed, would we say "the previous version" or "the earlier version"? Or is either fine? It would be great if the guidance and examples included this information. 

Also, as we are saying that either "earlier" or "previous" is fine, something about consistency needs to be added. Example:  "Use or earlier or previous instead of or lower to refer to all versions of a product that precede a particular release ...." Use "earlier" or "previous" consistently. Do not use a mix of "earlier" and "previous" within a document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f32b83a-84b5-c84b-655a-ab09b0833d87
* Version Independent ID: 0dae80c2-20c7-d7f4-ab56-914d860766c9
* Content: [earlier - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/e/earlier)
* Content Source: [styleguide/a-z-word-list-term-collections/e/earlier.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/e/earlier.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
Hello,

That’s a good question. In Microsoft content, our preference would be to specify which version—for example, “Windows 8.1” or “Microsoft Word 2013.”
That wording might not be as elegant as something like “the previous version,” but when the context is compatibility, upgrade path, or system requirements, users need specific information.

If your content/context doesn’t need to be that specific, [previous](https://ahdictionary.com/word/search.html?q=previous) might have a slight edge because its first dictionary meaning is “Existing or occurring before something else in time or order; prior.” But it’s a case of editorial judgment and what you and your team think is best for your audience and message.

Catherine
