### ISSUE TITLE
Zero article

### ISSUE THREAD

**Issue by rodrigyou** [MicrosoftDocs/microsoft-style-guide#52]
Do you have recommendations when to use zero articles? Do you recommend to drop "the" wherever possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b78bddec-b8a4-ade2-232b-c89068133b17
* Version Independent ID: 9136c473-b12a-bcf6-c25d-121e8c6677ab
* Content: [Formatting titles - Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/text-formatting/formatting-titles)
* Content Source: [styleguide/text-formatting/formatting-titles.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/text-formatting/formatting-titles.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
hi,
That's a great question. In general, in text, Microsoft style discourages the "zero article." 
The *Microsoft Writing Style Guide* aims to help writers create content for a worldwide audience. That is, it needs to be easy to localize and understandable to nonnative English speakers. One of the ways we do that is by including words that are "optional"--words that native speakers don't need in order to understand the meaning.

In the [Global communications > Writing tips](https://docs.microsoft.com/en-us/style-guide/global-communications/writing-tips) topic, it says:

Include articles, such as *the.* Articles help readers and translation software identify the nouns and modifiers in a sentence.
Examples
Empty the container.
The empty container

This guideline applies to all regular text (text the reader actually reads, as opposed to things like file and folder names, registry keys, things like that) including titles and headings.

A lot of the guidelines for writing [Headings](https://docs.microsoft.com/en-us/style-guide/scannable-content/headings) also apply to the titles of works.

I hope this helps.
Catherine
