### ISSUE TITLE
Using "is displayed"

### ISSUE THREAD

**Issue by KA-1** [MicrosoftDocs/microsoft-style-guide#8]
I would suggest that using "is displayed" is acceptable, because it refers to the system (which may be considered a passive object) and not an active user action. 
I suggest that using "is displayed" is preferable to using the verb "appears", because the definition of appears has associations with magic (DEF - Come into sight; become visible or noticeable, especially without apparent cause).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 947a7be7-0036-a242-4b97-caf8732e319e
* Version Independent ID: 0e8f6c1a-06a0-daed-0569-1d8022390baf
* Content: [appears, displays - Microsoft Style Guide](https://docs.microsoft.com/en-ca/style-guide/a-z-word-list-term-collections/a/appears-displays)
* Content Source: [styleguide/a-z-word-list-term-collections/a/appears-displays.md](https://github.com/MicrosoftDocs/microsoft-style-guide/blob/master/styleguide/a-z-word-list-term-collections/a/appears-displays.md)
* Product: **non-product-specific**
* GitHub Login: @pallep
* Microsoft Alias: **pallep**

**Comment by camind** [comment]
You raise an interesting point that “appears” has the magical connotation. That said, Microsoft style would still prefer “appears” because it’s an active verb and shorter than “is displayed.” I don’t think the association with magic is strong enough to overcome those reasons. I’m not sure, though, that “appears” can always replace “is displayed”—they’re not always interchangeable—so we’ll take another look at this.

I’m curious where your definition comes from. The [first definition in American Heritage]( https://ahdictionary.com/word/search.html?q=appear) is simply “To become visible; to be shown or included.” 
The usage note there is interesting. It lists a bunch of synonyms for “appear,” but doesn’t say anything about the “without apparent cause” aspect. 

Thanks for raising this!

**Comment by KA-1** [comment]
I got the definition from https://en.oxforddictionaries.com/definition/appear, which is a recommended reference for the Government of Canada.

BTW – Have you considered including a sender’s original message in your reply message? Some senders might not remember what they sent ☺
